@extends('layouts.admin');

@section('title')
Beranda
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <center>
            <h1>Selamat Datang!!!</h1>
            <h4>Website Ini Menyediakan tempat bagi anak yang membutuhkan pengasuhan</h4>
            <img src="{{asset('assets/images/other/content-bg.jpg')}}" alt="">
            </center>
            <h2>Sejarah</h2>
           <h3>Pondok Yatim</h3>
           <p>Berawal dari sebuah ide sederhana beberapa sahabat yang yang memiliki keprihatinan serta kepedulian yang sama terhadap anak yatim, piatu, dhuafa & warga yang kurang beruntung dalam menopang kesejahteraan hidup terlebih tanggung jawab mereka dalam mensukseskan pendidikan anak-anaknya, ditambah situasi warga Jakarta khususnya dan masyarakat Indonesia pada umumnya pasca krisis moneter  1997 dan berbuntut kerusuhan Mei 1998, yang berdampak pada krisis moral serta krisis kepemimpinan yang masih sangat terasa  hingga era tahun 2000 an sehingga memunculkan sebuah ide berupa  kegiatan bhakti sosial dengan harapan dapat meminimalisir mata rantai kemiskinan dan kebodohan sebagai akibat dampak krisis di atas.</p>
           <p>Ide tersebut rupanya tidak cukup sampai di forum silaturrahmi yang  saat itu bertepatan dengan rencana persiapan menyongsong tahun baru Hijriyah yang sudah menjadi kebiasaan rutin warga merangkainya dengan kegiatan santunan untuk anak yatim dhu’afa pada tanggal 10 Muharrom setiap tahunnya. Akhirnya kami melakukan shearing dengan tokoh masyarakat, bapak RT 003, bapak RW 06, juga bapak Lurah Kedoya Utara dan salah seorang staf beliau yang pada saat itu bertempat tinggal di lingkungan Rw.06 Kedoya Utara Jakarta Barat. Alhasil setelah mendapat dukungan warga sekitar dan beberapa kawan dari tetangga kampung maupun beberapa kawan yang kami pandang SDM nya mumpuni alias punya kecakapan dan kecukupan untuk membuat sekaligus mengoperasikan sebuah  yayasan yang berbadan hukum di Negara Kesatuan Republik Indonesia.</p>
           <p>Dari beberapa pertemuan silaturahmi yang dilakukan beberapa sahabat dan tokoh masyarakat yang ada disekitar RT 003 Rw 06 Kedoya Utara untuk membentuk yayasan yang mengacu pada amanat Undang-undang yayasan yang ditetapkan oleh pemerintah Republik Indonesia, Maka atas kehendak Alloh jua dan dukungan warga serta kawan-kawan, Alhamdulillah tepat pada tanggal 24 Agustus 2006 terbentuklah sebuah Yayasan yang memiliki legalitas Formal dengan nomer akte 125 Slamet Suryono Hadi S. SH sebagai lembaga non profit yang bergerak pada lingkup sosial keagamaan yang bertujuan untuk meningkatkan itensitas dakwah ke masyarakat pada umumnya dan secara khusus dapat membantu anggota masyarakat baik yang kurang mampu ataupun yang terkena musibah, maka yayasan ini diberi nama Yayasan Amal Sholeh Sejahtera dengan tiga departemen yaitu departemen keagamaan yang orientasinya untuk melakukan dakwah kepada masyarakat umum, dan depertemen sosial yang bertujuan untuk membantu masyarakat yang kurang mampu dan yang terkena musibah, kemudian departemen usaha yang berorientasi khusus mencari dana baik usaha riil maupun penggalangan dana ke masyarakat umum untuk memenuhi kebutuhan operasional Yayasan itu sendiri serta untuk  menyantuni anak anak yang kurang mampu  ( Yatim )</p>
           <p>Pada awal tahun 2007 semua departemen yayasan bergerak sesuai dengan tugas dan fungsinya terutama departemen usaha mulailah melakukan penggalang dana kepada masyarakat serta melakukan usaha usaha lainya untuk menopang operasional yayasan serta membantu anak anak yatim dan dhu’afa yang ada di sekitar sekretariat yayasan. Dan ternyata alhamdulillah kami tidak sendiri karena  begitu banyak masyarakat yang antusias ikut memberikan bantuanya untuk anak-anak yatim dan dhu’afa ini sehingga pada bulan Agustus 2007 Sekretariat Yayasan Amal Sholeh Sejahtera yang berlokasi di Gang Lekipali Jl. Raya Kedoya Utara Jakarta Barat. diresmikan oleh Bapak Lurah Kedoya Utara  yang sekaligus ikut andil dalam memberikan santunan kepada anak anak yang tidak mampu ini.  Dengan mulai mengalirnya bantuan dari para donatur, para da’i dan para sahabat serta warga masyarakat setempat, kemudian dengan  melihat kondisi anak anak yatim dan dhu’afa yang kami santuni sangatlah memprihatinkan maka akhirnya kami terinspirasi juga dengan kondisi ini, sehingga kamipun mulai memikirkan bagaimana meyiapkan asrama buat mereka agar mereka dapat diasuh dengan optimal dan maksimal untuk mengawal masa depan mereka, sementara kondisi kami sendiri tidak memiliki kemampuan yang lebih yang dapat kami berikan untuk mereka.</p>
           <p>Akhirnya pada awal tahun 2008 dengan bermodalkan niat yang tulus serta tekat yang kuat kami pun coba memberanikan diri untuk mengontrak sebuah rumah yang berdomisili di daerah Kembangan Jakarta Barat agar anak anak yang kurang beruntung ini dapat kami tampung dan kami asuh dengan baik,  maka kami pun  memberinya sebuah  nama  Pondok Yatim dan Dhu’afa ( PYD ) Yayasan Amal Sholeh Sejahtera.  Dan tepat pada tanggal 01 Mei 2008 Pondok Yatim dan Dhuafa ( Yayasan Amal Sholeh Sejahtera ) diresmikan lansung oleh Bapak Camat Kembangan Jakarta Barat, serta dihadiri juga oleh unsur dari Dinas Sosial Jakarta Barat dan semenjak itu Yayasan Amal Sholeh sejahtera berkonsentrasi penuh terhadap Pondok Yatim dan Dhu’afa dengan membentuk kepengurusan baru agar bisa lebih fokus dalam menangani anak-anak asuh di Asrama Yatim</p>
           <h2>Terima kasih para dermawan…</h2> 
           
        </div>
    </div>
</div>
@endsection